module.exports = {
  examples: [
    "examples/index",
    {
      type: "category",
      label: "Minute of Mayhem",
      link: { type: "doc", id: "examples/minute/index" },
      items: [
        "examples/minute/configure",
        "examples/minute/player-preferences",
      ],
    },
    "examples/lyra",
  ],
  framework: [
    "framework/index",
    "framework/automatic_login",
    "framework/automatic_parties",
    "framework/multiplayer_games",
    "framework/party_members",
    "framework/displaying_avatars",
    "framework/bind_friends_list",
    "framework/player_registration",
  ],
  systems: [
    "systems/index",
    "systems/api",
    "systems/async",
    "systems/user_id",
    "systems/identity",
    "systems/friends",
    "systems/presence",
    "systems/storage",
    "systems/user_cache",
    "systems/voice_chat",
  ],
  tools: [
    "tools/index",
    "tools/gameplay_debugger",
    "tools/voice_chat_debugger",
    "tools/console_commands",
    "tools/console_variables",
    "tools/profiling",
  ],
  support: [
    "support/index",
    "support/clone_from_gitlab",
    "support/migrate",
    {
      type: "category",
      label: "Troubleshooting",
      collapsed: false,
      items: [
        "support/troubleshooting/redpointeosconfig",
        "support/troubleshooting/unrealbuildtool",
        "support/troubleshooting/windows",
        "support/troubleshooting/macos",
        "support/troubleshooting/dynamicconfiglayer",
        "support/troubleshooting/steamcrash",
        "support/troubleshooting/steaminvite",
        "support/troubleshooting/anticheat",
        "support/troubleshooting/room_transactions_throttled",
        "support/troubleshooting/netdrivers_oculusxr",
      ],
    },
    "support/blueprints_only",
    "support/advanced_configuration",
    "support/additional_sdk_install_locations",
    "support/attribution",
    "support/uninstall",
  ],
  matchmaking: [
    "matchmaking/index",
    {
      type: "category",
      label: "Features",
      collapsed: false,
      items: [
        "matchmaking/skill_configuration",
        "matchmaking/dedicated_server_configuration",
      ],
    },
    {
      type: "category",
      label: "Matchmaking with Blueprints",
      link: { type: "doc", id: "matchmaking/blueprints/index" },
      items: [
        "matchmaking/blueprints/matchmaker",
        "matchmaking/blueprints/listen_for_events",
        "matchmaking/blueprints/ready_up_players",
        "matchmaking/blueprints/runtime_information",
        "matchmaking/blueprints/submitting_match_results",
      ],
    },
    {
      type: "category",
      label: "Matchmaking with C++",
      link: { type: "doc", id: "matchmaking/cpp/index" },
      items: [
        "matchmaking/cpp/queue_to_matchmaking",
        "matchmaking/cpp/cancelling_matchmaking",
        "matchmaking/cpp/submitting_match_results",
      ],
    },
    "matchmaking/algorithm_flow",
  ],
  dedicated_servers: [
    "dedis/index",
    "dedis/avoiding_public_clouds",
    "dedis/regions_clusters",
    "dedis/preparing_your_game_server",
    "dedis/securing_your_network",
    "dedis/creating_your_cluster",
    "dedis/adding_nodes",
    "dedis/testing_deployment",
    "dedis/setting_up_autoscaling",
    "dedis/updating_your_game_client",
    "dedis/bursting_into_cloud",
    "dedis/automating_deployments",
    "dedis/playfab",
  ],
  ossv1: [
    "ossv1/index",
    {
      type: "category",
      label: "Identity",
      items: [
        "ossv1/identity/authentication",
        "ossv1/identity/linking",
        {
          type: "doc",
          label: "Get the user ID of a player controller",
          id: "setup/networking/uniquenetid",
        },
        "ossv1/identity/user_attributes",
        "ossv1/identity/serializing",
      ],
    },
    {
      type: "category",
      label: "Friends",
      items: [
        "ossv1/friends/retrieving",
        "ossv1/friends/invites",
        "ossv1/friends/deleting",
        "ossv1/friends/recent_players",
        "ossv1/friends/blocked_players",
        "ossv1/friends/blocked_players_manage",
      ],
    },
    {
      type: "category",
      label: "Avatars",
      items: ["ossv1/avatars/fetching"],
    },
    {
      type: "category",
      label: "Parties",
      items: [
        "ossv1/parties/creating",
        "ossv1/parties/status",
        "ossv1/parties/inviting",
        "ossv1/parties/data",
        "ossv1/parties/events",
      ],
    },
    {
      type: "category",
      label: "Presence",
      items: [
        "ossv1/presence/updating",
        "ossv1/presence/querying",
        "ossv1/presence/parties",
        "ossv1/presence/sessions",
        "ossv1/presence/connection_status",
      ],
    },
    {
      type: "category",
      label: "Sessions",
      items: [
        "ossv1/sessions/creating",
        "ossv1/sessions/finding",
        "ossv1/sessions/joining",
        "ossv1/sessions/destroying",
        "ossv1/sessions/reconnecting",
        "ossv1/sessions/attributes",
        "ossv1/sessions/lifecycle",
      ],
    },
    {
      type: "category",
      label: "Lobbies",
      items: [
        "ossv1/lobbies/creating",
        "ossv1/lobbies/data",
        "ossv1/lobbies/finding",
        "ossv1/lobbies/joining",
        "ossv1/lobbies/destroying",
      ],
    },
    {
      type: "category",
      label: "User Info",
      items: [
        "ossv1/user/id",
        "ossv1/user/displayname",
        "ossv1/user/external_id",
        {
          type: "doc",
          label: "Get the user ID of a player controller",
          id: "setup/networking/uniquenetid",
        },
      ],
    },
    {
      type: "category",
      label: "Stats",
      items: [
        "ossv1/stats/configuring",
        "ossv1/stats/updating",
        "ossv1/stats/querying",
      ],
    },
    {
      type: "category",
      label: "Achievements",
      items: ["ossv1/achievements/querying", "ossv1/achievements/notifying"],
    },
    {
      type: "category",
      label: "Leaderboards",
      items: ["ossv1/leaderboards/querying"],
    },
    {
      type: "category",
      label: "External UI",
      items: ["ossv1/external_ui/friends", "ossv1/external_ui/invite"],
    },
    {
      type: "category",
      label: "E-commerce",
      items: [
        "ossv1/ecom/offers",
        "ossv1/ecom/purchasing",
        "ossv1/ecom/entitlements",
      ],
    },
    {
      type: "category",
      label: "User Cloud",
      items: [
        "ossv1/user_cloud/reading",
        "ossv1/user_cloud/writing",
        "ossv1/user_cloud/precache",
      ],
    },
    {
      type: "category",
      label: "Title File",
      items: [
        "ossv1/title_file/uploading",
        "ossv1/title_file/anonymous",
        "ossv1/title_file/reading",
      ],
    },
    {
      type: "category",
      label: "Voice Chat",
      items: [
        "ossv1/voice_chat/index",
        "ossv1/voice_chat/control",
        "ossv1/voice_chat/parties",
        "ossv1/voice_chat/listen_servers",
        "ossv1/voice_chat/dedicated_servers",
      ],
    },
  ],
  blueprint_reference: [
    {
      type: "autogenerated",
      dirName: "ossv1/blueprints/reference",
    },
  ],
  setup: [
    "setup/index",
    {
      type: "category",
      label: "Platform setup",
      items: [
        "setup/platforms/steam",
        "setup/platforms/discord",
        "setup/platforms/epic",
        "setup/platforms/gog",
        "setup/platforms/itchio",
        "setup/platforms/meta",
        "setup/platforms/google",
        "setup/platforms/apple",
        "setup/platforms/consoles",
      ],
    },
    {
      type: "category",
      label: "Authentication",
      items: [
        "auth/configuration",
        "auth/custom_ui",
        "auth/dev_auth_tool_usage",
        "auth/write_your_own_authentication_graph",
        {
          type: "category",
          label: "Cross-platform accounts:",
          collapsed: false,
          items: [
            "auth/xplat/epic",
            "auth/xplat/simplefp",
            "auth/write_your_own_cross_platform_account_provider",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Cross-platform setup",
      items: ["setup/crossplatform/friends", "setup/crossplatform/invites"],
    },
    {
      type: "category",
      label: "Networking & Anti-Cheat",
      items: [
        "setup/networking/configuration",
        "setup/networking/p2p_vs_ip",
        "setup/networking/authentication",
        "setup/networking/anticheat",
        "setup/networking/uniquenetid",
        "setup/networking/server_travel",
      ],
    },
    "setup/next_steps",
  ],
};
