name: Redpoint Games Docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build Docs
        run: |
          corepack enable
          npx update-browserslist-db@latest
          yarn
          yarn build
      - name: Upload Built Docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          if-no-files-found: error
          path: |
            build/

  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: ["build"]
    if: github.ref == 'refs/heads/main' && github.repository == 'RedpointGames/docs'
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Built Docs
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: build/
          merge-multiple: true
      - name: Publish Docs
        run: |
          cp _redirects build/_redirects
          corepack enable
          yarn
          yarn wrangler pages deploy ./build --project-name redpoint-games-docs --branch main
